name: Build Decode (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Qt 6 and build tools
      run: |
        brew update
        brew install cmake ninja qt6 create-dmg openssl

    - name: Configure with CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$(brew --prefix qt6)"

    - name: Build project
      run: cmake --build build

    - name: Make DMG
      run: |
        APP_NAME="Decode"
        VERSION="${{ github.ref_name || 'dev' }}-${{ github.run_number }}"
        APP_BUNDLE="build/${APP_NAME}.app"
        DMG_NAME="${APP_NAME}-${VERSION}.dmg"
        mkdir -p build/dmg_temp
        cp -R "${APP_BUNDLE}" build/dmg_temp/
        ln -s /Applications build/dmg_temp/Applications
        hdiutil create -volname "${APP_NAME} Installer" \
          -srcfolder build/dmg_temp \
          -ov -format UDZO build/${DMG_NAME}
        echo "DMG_NAME=${DMG_NAME}" >> $GITHUB_ENV

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DMG_NAME }}
        path: build/${{ env.DMG_NAME }}
