name: Cross-Platform Build & Package

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Package binaries
        run: |
          cd build
          zip -r ../Decode-${{ matrix.os }}-${{ matrix.arch }}.zip . || powershell Compress-Archive -Path * -DestinationPath ../Decode-${{ matrix.os }}-${{ matrix.arch }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Decode-${{ matrix.os }}-${{ matrix.arch }}
          path: Decode-${{ matrix.os }}-${{ matrix.arch }}.zip
