name: Static Qt Build (with aqtinstall)

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            arch: gcc_64
          - os: windows-latest
            target: windows
            arch: win64_msvc2019_64
          - os: macos-latest
            target: mac
            arch: clang_64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt with aqtinstall
        run: |
          aqt install-qt ${{ matrix.target }} desktop 6.6.2 ${{ matrix.arch }} --outputdir ${{ github.workspace }}/Qt
        shell: bash

      - name: Configure CMake project
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/Qt/6.6.2/${{ matrix.arch }}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DQt6_STATIC=ON

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package
        run: |
          cd build
          zip -r ../Decode-static-${{ matrix.os }}.zip . || powershell Compress-Archive -Path * -DestinationPath ../Decode-static-${{ matrix.os }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Decode-static-${{ matrix.os }}
          path: Decode-static-${{ matrix.os }}.zip
